"""initial

Revision ID: 202506031921
Revises:
Create Date: 2025-06-03 19:21:08.773922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202506031921'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('event_number', sa.Integer(), nullable=False),
    sa.Column('number_of_items', sa.Integer(), nullable=True),
    sa.Column('vendor_beta_market_id', sa.String(), nullable=False),
    sa.Column('vendor_alpha_url', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'start_time', name='unique_venue_start_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
