"""add-machine-id-to-opportunities

Revision ID: 202506291422
Revises: 202506131835
Create Date: 2025-06-29 14:22:50.945314

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202506291422"
down_revision: Union[str, None] = "202506131835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opportunities", sa.Column("machine_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "opportunities", "machines", ["machine_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "opportunities", type_="foreignkey")
    op.drop_column("opportunities", "machine_id")
    # ### end Alembic commands ###
