import os

from dotenv import load_dotenv

from libs.utils.ssm import get_secrets

load_dotenv(verbose=True, override=True)

# Parameter Store Constants
PARAMETER_STORE_DIR = "/arbee-secrets"
PARAMETER_STORE_KEYS = [
    "TRACKER_FILE_ID",
    "AWS_SNS_OPPS_TOPIC_ARN",
    "DISCORD_CLOUBEE_WEBHOOK_ID",
    "DISCORD_CLOUBEE_WEBHOOK_TOKEN",
    "DISCORD_DAILY_EVENTS_WEBHOOK_ID",
    "DISCORD_DAILY_EVENTS_WEBHOOK_TOKEN",
    "DISCORD_PLACED_ORDERS_WEBHOOK_ID",
    "DISCORD_PLACED_ORDERS_WEBHOOK_TOKEN",
    "DATABASE_URL",
]
PARAMETER_STORE_MAPPING = {key: f"{PARAMETER_STORE_DIR}/{key}" for key in PARAMETER_STORE_KEYS}


# Load local .env-based secrets
VENDOR_BETA_USER = os.getenv("VENDOR_BETA_USER")
VENDOR_BETA_PASS = os.getenv("VENDOR_BETA_PASS")
VENDOR_ALPHA_USER = os.getenv("VENDOR_ALPHA_USER").lower()
VENDOR_ALPHA_PASS = os.getenv("VENDOR_ALPHA_PASS")

VENDOR_BETA_API_KEY = os.getenv("VENDOR_BETA_API_KEY")

TELEGRAM_AUTH_TOKEN = os.getenv("TELEGRAM_AUTH_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION")

MACHINE = os.getenv("MACHINE") or os.getenv("OPERATOR")
assert MACHINE is not None, "Missing required environment variable: MACHINE"
MACHINE = MACHINE.lower()

# Load AWS SSM secrets
secrets = get_secrets(list(PARAMETER_STORE_MAPPING.values()))

TRACKER_FILE_ID = secrets[PARAMETER_STORE_MAPPING["TRACKER_FILE_ID"]]

AWS_SNS_OPPS_TOPIC_ARN = secrets[PARAMETER_STORE_MAPPING["AWS_SNS_OPPS_TOPIC_ARN"]]

DISCORD_CLOUBEE_WEBHOOK_ID = secrets[PARAMETER_STORE_MAPPING["DISCORD_CLOUBEE_WEBHOOK_ID"]]
DISCORD_CLOUBEE_WEBHOOK_TOKEN = secrets[PARAMETER_STORE_MAPPING["DISCORD_CLOUBEE_WEBHOOK_TOKEN"]]

DISCORD_DAILY_EVENTS_WEBHOOK_ID = secrets[PARAMETER_STORE_MAPPING["DISCORD_DAILY_EVENTS_WEBHOOK_ID"]]
DISCORD_DAILY_EVENTS_WEBHOOK_TOKEN = secrets[
    PARAMETER_STORE_MAPPING["DISCORD_DAILY_EVENTS_WEBHOOK_TOKEN"]
]

DISCORD_PLACED_ORDERS_WEBHOOK_ID = secrets[PARAMETER_STORE_MAPPING["DISCORD_PLACED_ORDERS_WEBHOOK_ID"]]
DISCORD_PLACED_ORDERS_WEBHOOK_TOKEN = secrets[
    PARAMETER_STORE_MAPPING["DISCORD_PLACED_ORDERS_WEBHOOK_TOKEN"]
]
DB_URL = secrets[PARAMETER_STORE_MAPPING["DATABASE_URL"]]
